# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Update Module Source Files with Current Branch
        shell: powershell
        run: |
          try
          {
            Import-Module StigRepo -Force
          }
          catch 
          {
            Install-Module StigRepo -Force
            Import-Module StigRepo -Force
          }

          $ModulePath = (Get-Module -Name StigRepo).Path
          $ModuleRoot = Split-Path -Path $ModulePath -Parent
          $localSourceFiles = Get-Childitem "$moduleRoot\Module\*.ps1"
          $newSourceFiles = Get-ChildItem -Path "${env:GITHUB_WORKSPACE}\source\module\*.ps1"
          Remove-Module StigRepo -Force

          foreach ($file in $localSourceFiles)
          {
            $newSourceFile = $newSourceFiles | Where {$_.name -eq $file.Name}
            $newContent = Get-Content -Path $newSourceFile.FullName -encoding utf8
            Set-Content -Path $file.FullName -Value $newContent -Force
          }
          Import-Module StigRepo -Force

      - name: StigRepo Build
        shell: powershell
        run: |
          Remove-Item -Path C:\SCAR -Recurse -Force -Confirm:$False
          New-Item -ItemType Directory -Path C:\SCAR
          Set-Location "C:\SCAR"
          Import-Module StigRepo -Force
          Initialize-StigRepo -RootPath "C:\SCAR"
          Remove-Item C:\SCAR\Resources\Modules\StigRepo -Force
          Copy-Item -Path "C:\Program Files\WindowsPowerShell\Modules\StigRepo" -Destination "C:\SCAR\Resources\Modules" -Force
          New-SystemData -Scope 'Full'
          Sync-DscModules -Force
          Set-WinRMConfig
          Start-DscBuild
          Get-StigChecklists

      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: STIG_Checklists
          path: 'C:\Scar\Artifacts\Stig Checklists'
